/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2019-03-17 11:53:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.jsp.default_.ui;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class casLoginView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar", Long.valueOf(1389675724000L));
    _jspx_dependants.put("jar:file:/D:/apache-tomcat-CAS/webapps/cas/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1386780824000L));
    _jspx_dependants.put("jar:file:/D:/apache-tomcat-CAS/webapps/cas/WEB-INF/lib/spring-webmvc-3.2.6.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1386780824000L));
    _jspx_dependants.put("jar:file:/D:/apache-tomcat-CAS/webapps/cas/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1331782536000L));
    _jspx_dependants.put("jar:file:/D:/apache-tomcat-CAS/webapps/cas/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005fhtmlEscape_005fcommandName_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fpassword_0026_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fid_005fhtmlEscape_005felement_005fcssClass_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005fhtmlEscape_005fcommandName_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fpassword_0026_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fid_005fhtmlEscape_005felement_005fcssClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005fhtmlEscape_005fcommandName_005fclass.release();
    _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fpassword_0026_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fid_005fhtmlEscape_005felement_005fcssClass_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9; IE=8; IE=7; IE=EDGE\">\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\r\n");
      out.write("\t<title>品优购，欢迎登录</title>\r\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/webbase.css\" />\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/pages-login.css\" />\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"login-box\">\r\n");
      out.write("\t\t<!--head-->\r\n");
      out.write("\t\t<div class=\"py-container logoArea\">\r\n");
      out.write("\t\t\t<a href=\"\" class=\"logo\"></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--loginArea-->\r\n");
      out.write("\t\t<div class=\"loginArea\">\r\n");
      out.write("\t\t\t<div class=\"py-container login\">\r\n");
      out.write("\t\t\t\t<div class=\"loginform\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"sui-nav nav-tabs tab-wraped\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#index\" data-toggle=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>扫描登录</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#profile\" data-toggle=\"tab\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>账户登录</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<div class=\"tab-content tab-wraped\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"index\" class=\"tab-pane\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>二维码登录，暂为官网二维码</p>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"img/wx_cz.jpg\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"profile\" class=\"tab-pane  active\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <form class=\"sui-form\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t ");
      //  form:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005fhtmlEscape_005fcommandName_005fclass.get(org.springframework.web.servlet.tags.form.FormTag.class);
      boolean _jspx_th_form_005fform_005f0_reused = false;
      try {
        _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
        _jspx_th_form_005fform_005f0.setParent(null);
        // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(51,8) null
        _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "sui-form");
        // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(51,8) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setMethod("post");
        // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(51,8) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setId("fm1");
        // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(51,8) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setCommandName((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${commandName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(51,8) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_form_005fform_005f0.setHtmlEscape("true");
        int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
          if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\"><span class=\"add-on loginname\"></span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<!-- <input id=\"prependedInput\" type=\"text\" placeholder=\"邮箱/用户名/手机号\" \r\n");
              out.write("\t\t\t\t\t\t\t\t\tclass=\"span2 input-xfat\"> -->\r\n");
              out.write("\t\t\t\t\t\t\t\t    ");
              if (_jspx_meth_form_005finput_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"input-prepend\"><span class=\"add-on loginpwd\"></span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<!--<input id=\"prependedInput\" type=\"password\" placeholder=\"请输入密码\" class=\"span2 input-xfat\">-->\r\n");
              out.write("\t\t\t\t\t\t\t\t    ");
              if (_jspx_meth_form_005fpassword_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
                return;
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"setting\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<label class=\"checkbox inline\">\r\n");
              out.write("          <input name=\"m1\" type=\"checkbox\" value=\"2\" checked=\"\"> \r\n");
              out.write("          自动登录\r\n");
              out.write("        </label>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<span class=\"forget\">忘记密码？</span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<!--错误提示-->\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\t");
              //  form:errors
              org.springframework.web.servlet.tags.form.ErrorsTag _jspx_th_form_005ferrors_005f0 = (org.springframework.web.servlet.tags.form.ErrorsTag) _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fid_005fhtmlEscape_005felement_005fcssClass_005fnobody.get(org.springframework.web.servlet.tags.form.ErrorsTag.class);
              boolean _jspx_th_form_005ferrors_005f0_reused = false;
              try {
                _jspx_th_form_005ferrors_005f0.setPageContext(_jspx_page_context);
                _jspx_th_form_005ferrors_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
                // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(72,10) name = path type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f0.setPath("*");
                // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(72,10) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f0.setId("msg");
                // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(72,10) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f0.setCssClass("errors");
                // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(72,10) name = element type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f0.setElement("div");
                // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(72,10) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
                _jspx_th_form_005ferrors_005f0.setHtmlEscape("false");
                int[] _jspx_push_body_count_form_005ferrors_005f0 = new int[] { 0 };
                try {
                  int _jspx_eval_form_005ferrors_005f0 = _jspx_th_form_005ferrors_005f0.doStartTag();
                  if (_jspx_th_form_005ferrors_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                    return;
                  }
                } catch (java.lang.Throwable _jspx_exception) {
                  while (_jspx_push_body_count_form_005ferrors_005f0[0]-- > 0)
                    out = _jspx_page_context.popBody();
                  _jspx_th_form_005ferrors_005f0.doCatch(_jspx_exception);
                } finally {
                  _jspx_th_form_005ferrors_005f0.doFinally();
                }
                _005fjspx_005ftagPool_005fform_005ferrors_0026_005fpath_005fid_005fhtmlEscape_005felement_005fcssClass_005fnobody.reuse(_jspx_th_form_005ferrors_005f0);
                _jspx_th_form_005ferrors_005f0_reused = true;
              } finally {
                org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005ferrors_005f0, _jsp_getInstanceManager(), _jspx_th_form_005ferrors_005f0_reused);
              }
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"logined\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<!--<a class=\"sui-btn btn-block btn-xlarge btn-danger\" href=\"home-index.html\" >登&nbsp;&nbsp;录</a>-->\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"lt\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginTicket}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"execution\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flowExecutionKey}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"_eventId\" value=\"submit\" />\r\n");
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<input class=\"sui-btn btn-block btn-xlarge btn-danger\" \r\n");
              out.write("\t\t\t\t\t\t\t\t\tname=\"submit\" accesskey=\"l\" value=\"登&nbsp;&nbsp;录\" tabindex=\"4\" type=\"submit\" />\r\n");
              out.write("   \r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t<!-- </form> -->\r\n");
              out.write("\t\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_form_005fform_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fform_005fform_0026_005fmethod_005fid_005fhtmlEscape_005fcommandName_005fclass.reuse(_jspx_th_form_005fform_005f0);
        _jspx_th_form_005fform_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fform_005f0_reused);
      }
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"otherlogin\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"types\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><img src=\"img/qq.png\" width=\"35px\" height=\"35px\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><img src=\"img/sina.png\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><img src=\"img/ali.png\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><img src=\"img/weixin.png\" /></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"register\"><a href=\"register.html\" target=\"_blank\">立即注册</a></span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--foot-->\r\n");
      out.write("\t\t<div class=\"py-container copyright\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>关于我们</li>\r\n");
      out.write("\t\t\t\t<li>联系我们</li>\r\n");
      out.write("\t\t\t\t<li>联系客服</li>\r\n");
      out.write("\t\t\t\t<li>商家入驻</li>\r\n");
      out.write("\t\t\t\t<li>营销中心</li>\r\n");
      out.write("\t\t\t\t<li>手机品优购</li>\r\n");
      out.write("\t\t\t\t<li>销售联盟</li>\r\n");
      out.write("\t\t\t\t<li>品优购社区</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"address\">地址：北京市昌平区建材城西路金燕龙办公楼一层 邮编：100096 电话：400-618-4000 传真：010-82935100</div>\r\n");
      out.write("\t\t\t<div class=\"beian\">京ICP备08001421号京公网安备110108007702\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery.easing/jquery.easing.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/sui/sui.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/plugins/jquery-placeholder/jquery.placeholder.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"js/pages/login.js\"></script>\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_form_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_form_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_form_005finput_005f0_reused = false;
    try {
      _jspx_th_form_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setId("username");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) name = size type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setSize("25");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) null
      _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "type", "text");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) null
      _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "placeholder", "邮箱/用户名/手机号");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) null
      _jspx_th_form_005finput_005f0.setDynamicAttribute(null, "class", "span2 input-xfat");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setTabindex("1");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) name = accesskey type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setAccesskey((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userNameAccessKey}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setPath("username");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setAutocomplete("off");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(55,12) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005finput_005f0.setHtmlEscape("true");
      int[] _jspx_push_body_count_form_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005finput_005f0 = _jspx_th_form_005finput_005f0.doStartTag();
        if (_jspx_th_form_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005finput_0026_005ftype_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody.reuse(_jspx_th_form_005finput_005f0);
      _jspx_th_form_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_form_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_form_005fpassword_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  form:password
    org.springframework.web.servlet.tags.form.PasswordInputTag _jspx_th_form_005fpassword_005f0 = (org.springframework.web.servlet.tags.form.PasswordInputTag) _005fjspx_005ftagPool_005fform_005fpassword_0026_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody.get(org.springframework.web.servlet.tags.form.PasswordInputTag.class);
    boolean _jspx_th_form_005fpassword_005f0_reused = false;
    try {
      _jspx_th_form_005fpassword_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fpassword_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(62,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setId("password");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(62,12) name = size type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setSize("25");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(62,12) null
      _jspx_th_form_005fpassword_005f0.setDynamicAttribute(null, "placeholder", "请输入密码");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(62,12) null
      _jspx_th_form_005fpassword_005f0.setDynamicAttribute(null, "class", "span2 input-xfat");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(62,12) name = tabindex type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setTabindex("2");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(62,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setPath("password");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(62,12) name = accesskey type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setAccesskey((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${passwordAccessKey}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(62,12) name = htmlEscape type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setHtmlEscape("true");
      // /WEB-INF/view/jsp/default/ui/casLoginView.jsp(62,12) name = autocomplete type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fpassword_005f0.setAutocomplete("off");
      int[] _jspx_push_body_count_form_005fpassword_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fpassword_005f0 = _jspx_th_form_005fpassword_005f0.doStartTag();
        if (_jspx_th_form_005fpassword_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fpassword_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fpassword_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fpassword_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fform_005fpassword_0026_005ftabindex_005fsize_005fplaceholder_005fpath_005fid_005fhtmlEscape_005fclass_005fautocomplete_005faccesskey_005fnobody.reuse(_jspx_th_form_005fpassword_005f0);
      _jspx_th_form_005fpassword_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_form_005fpassword_005f0, _jsp_getInstanceManager(), _jspx_th_form_005fpassword_005f0_reused);
    }
    return false;
  }
}
